name: DEPLOY DE SITE COM GITHUB ACTIONS 

on:
  push:
    branches: ["main"]

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        #Atualizado para @v4 (garante compatibilidade com o ambiente atual)
        - name: Checkout do código
          uses: actions/checkout@v4

        #Atualizado para @v5
        - name: configurar o GitHub Pages
          uses: actions/configure-pages@v5

        #atualizado para @v3
        - name: Upload dos arq do site
          uses: actions/upload-pages-artifact@v3
          with:
            path: '.'

        #atualizado para @v4
        - name: Publicar no github pages
          id: deployment
          uses: actions/deploy-pages@v4
          
